### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ps1c00** [micahvandeusen/gMSADumper#14]
python gMSADumper.py -d local.com -u '*******' -p '******'
Users or groups who can read password for QLIK3$:
Traceback (most recent call last):
  File "/opt/Tools/gMSADumper/gMSADumper.py", line 133, in <module>
    main()
  File "/opt/Tools/gMSADumper/gMSADumper.py", line 101, in main
    for dacl in SR_SECURITY_DESCRIPTOR(data=entry['msDS-GroupMSAMembership'].raw_values[0])['Dacl']['Data']:
                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by MiMaz7707** [comment]
Hello,

Im facing the same problem

**Comment by MiMaz7707** [comment]
Hello,

it works after using the first commit files.
