### ISSUE TITLE
TypeError: Missing required parameter 'digestmod' - pythom3.9

### ISSUE THREAD

**Issue by j0rg3k** [micahvandeusen/gMSADumper#5]
python3 gMSADumper.py -d xxx,yyyy -u 'user.name' -p 'some password'                                                                                                            
Traceback (most recent call last):
  File "/home/kaliuser/Documents/htb/ctf/search/impacket/gMSADumper.py", line 101, in <module>
    main()
  File "/home/kaliuser/Documents/htb/ctf/search/impacket/gMSADumper.py", line 77, in main
    conn = Connection(server, user='{}\\{}'.format(args.domain, args.username), password=args.password, authentication=NTLM, auto_bind=True)
  File "/usr/local/lib/python3.9/dist-packages/ldap3/core/connection.py", line 321, in __init__
    self.do_auto_bind()
  File "/usr/local/lib/python3.9/dist-packages/ldap3/core/connection.py", line 338, in do_auto_bind
    self.bind(read_server_info=True)
  File "/usr/local/lib/python3.9/dist-packages/ldap3/core/connection.py", line 563, in bind
    response = self.do_ntlm_bind(controls)
  File "/usr/local/lib/python3.9/dist-packages/ldap3/core/connection.py", line 1302, in do_ntlm_bind
    request = bind_operation(self.version, 'SICILY_RESPONSE_NTLM', ntlm_client, result['server_creds'])
  File "/usr/local/lib/python3.9/dist-packages/ldap3/operation/bind.py", line 81, in bind_operation
    server_creds = name.create_authenticate_message()
  File "/usr/local/lib/python3.9/dist-packages/ldap3/utils/ntlm.py", line 379, in create_authenticate_message
    nt_challenge_response = self.compute_nt_response()
  File "/usr/local/lib/python3.9/dist-packages/ldap3/utils/ntlm.py", line 485, in compute_nt_response
    response_key_nt = self.ntowf_v2()
  File "/usr/local/lib/python3.9/dist-packages/ldap3/utils/ntlm.py", line 497, in ntowf_v2
    return hmac.new(password_digest, (self.user_name.upper() + self.user_domain).encode('utf-16-le')).digest()
  File "/usr/lib/python3.9/hmac.py", line 170, in new
    return HMAC(key, msg, digestmod)
  File "/usr/lib/python3.9/hmac.py", line 56, in __init__
    raise TypeError("Missing required parameter 'digestmod'.")
TypeError: Missing required parameter 'digestmod'.

**Comment by micahvandeusen** [comment]
This is an impacket issue. Try: python3 -m pip install impacket --upgrade --user

**Comment by j0rg3k** [comment]
I tried this before opening this issue and it didn’t work

**Comment by micahvandeusen** [comment]
If your not already, try installing everything in a Python virtual environment.
